### Site Settings ###
title               : ProbInG
description         : Probabilistic Invariant Generation @ TU Wien
baseurl             : ""
repository          : probing-lab/probing-lab.github.io
remote_theme        : YoussefRaafatNasry/portfolYOU@v2.2.2


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/publications-tags.html
  - pages/posts-tags.html
  - pages/404.html
  - pages/index.html


### Author Info ###
author:
  name              : ProbInG
  github            : probing-lab
  twitter           : probing_lab


### Posts ###
permalink: /posts/:title


### Collections ###
collections:
  people:
    output: true
    permalink: /people/:name
  publications:
    output: true
    permalink: /publications/:name
  tools:
    output: true
    permalink: /tools/:name


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "people"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "publications"
    values:
        layout: "page"
  - scope:
      path: ""
      type: "tools"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "page"
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
