### Site Settings ###
title               : ProbInG
description         : Probabilistic Invariant Generation @ TU Wien
baseurl             : ""
repository          : probing-lab/probing-lab.github.io
remote_theme        : YoussefRaafatNasry/portfolYOU@v2.2.2


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : ProbInG
  image             : https://images.unsplash.com/photo-1441974231531-c6227db76b6e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1351&q=80
  github            : probing-lab
  twitter           : probing_lab


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  people:
    output: true
    permalink: /people/:name


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "people"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
